/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as apeSol from "./Ape.sol";
export * as votesSol from "./Votes.sol";
export * as event from "./event";
export { DealClient__factory } from "./DealClient__factory";
