/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as votesSol from "./Votes.sol";
export * as event from "./event";
export { RewardToken__factory } from "./RewardToken__factory";
