/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as apeSol from "./Ape.sol";
export type { apeSol };
import type * as votesSol from "./Votes.sol";
export type { votesSol };
import type * as event from "./event";
export type { event };
export type { DealClient } from "./DealClient";
