/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Actor } from "./Actor";
export type { BigInts } from "./BigInts";
export type { FilAddresses } from "./FilAddresses";
