/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../../common";
import type {
  BigInts,
  BigIntsInterface,
} from "../../../../../../@zondax/filecoin-solidity/contracts/v0.8/utils/BigInts";

const _abi = [
  {
    inputs: [],
    name: "NegativeValueNotAllowed",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122032b4ad74e519127d79c62ab4cc67b27f84a64fc0919cd5c9213800ecffbf18b964736f6c63430008110033";

type BigIntsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BigIntsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BigInts__factory extends ContractFactory {
  constructor(...args: BigIntsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BigInts> {
    return super.deploy(overrides || {}) as Promise<BigInts>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BigInts {
    return super.attach(address) as BigInts;
  }
  override connect(signer: Signer): BigInts__factory {
    return super.connect(signer) as BigInts__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BigIntsInterface {
    return new utils.Interface(_abi) as BigIntsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BigInts {
    return new Contract(address, _abi, signerOrProvider) as BigInts;
  }
}
