/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../../common";
import type {
  FilAddresses,
  FilAddressesInterface,
} from "../../../../../../@zondax/filecoin-solidity/contracts/v0.8/utils/FilAddresses";

const _abi = [
  {
    inputs: [],
    name: "InvalidAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207dd097303e1476929d3f4261eb34853a289e58321e7afc5ec994e8f95c28133a64736f6c63430008130033";

type FilAddressesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FilAddressesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FilAddresses__factory extends ContractFactory {
  constructor(...args: FilAddressesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<FilAddresses> {
    return super.deploy(overrides || {}) as Promise<FilAddresses>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): FilAddresses {
    return super.attach(address) as FilAddresses;
  }
  override connect(signer: Signer): FilAddresses__factory {
    return super.connect(signer) as FilAddresses__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FilAddressesInterface {
    return new utils.Interface(_abi) as FilAddressesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FilAddresses {
    return new Contract(address, _abi, signerOrProvider) as FilAddresses;
  }
}
